#!/bin/bash

echo "🚀 Starting ARAM Education Platform..."
echo ""
echo "Make sure you have completed the setup steps:"
echo "1. ✓ npm install (dependencies installed)"
echo "2. ✓ npx prisma generate (Prisma client generated)"
echo "3. ✓ npx prisma db push (database created)"
echo "4. ✓ Government user created"
echo "5. ✓ Test teacher created"
echo ""
echo "Starting development server..."
echo ""
echo "📝 Login credentials:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "👔 Government Portal:"
echo "   Email: govoff123@gmail.com"
echo "   Password: admin123"
echo ""
echo "👨‍🏫 Teacher Portal:"
echo "   Email: teacher@test.com"
echo "   Password: teacher123"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🌐 Opening http://localhost:3000 in your browser..."
echo ""
echo "Press Ctrl+C to stop the server"
echo ""

npm run dev
