import { NextRequest, NextResponse } from 'next/server'

export async function POST(req: NextRequest) {
  try {
    const body = await req.json()
    const { question } = body

    if (!question || typeof question !== 'string') {
      return NextResponse.json(
        { error: 'Question is required' },
        { status: 400 }
      )
    }

    // OpenAI (ChatGPT) API integration for doubt clarification ONLY
    const apiKey = process.env.OPENAI_API_KEY

    if (!apiKey) {
      console.error('OPENAI_API_KEY not found in environment')
      return NextResponse.json(
        { error: 'AI service is not configured' },
        { status: 500 }
      )
    }

    console.log('=== AI Doubt Request (OpenAI/ChatGPT) ===')
    console.log('Question:', question)
    console.log('Model: gpt-4o-mini')
    console.log('API Key:', apiKey.substring(0, 10) + '...')

    const response = await fetch(
      `https://api.openai.com/v1/chat/completions`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`
        },
        body: JSON.stringify({
          model: 'gpt-4o-mini',
          messages: [
            {
              role: 'system',
              content: 'You are a helpful educational assistant for the ARAM Education Platform. Answer student questions clearly and concisely about educational topics (physics, chemistry, biology, mathematics, etc.). Provide explanations with examples when helpful. Keep responses educational and focused on learning.'
            },
            {
              role: 'user',
              content: question
            }
          ],
          temperature: 0.7,
          max_tokens: 2048
        })
      }
    )

    const data = await response.json()

    console.log('OpenAI API Response Status:', response.status)

    if (!response.ok) {
      console.error('=== OPENAI API ERROR ===')
      console.error('Full Error:', JSON.stringify(data, null, 2))
      return NextResponse.json(
        { error: 'Failed to get response from AI service', details: data },
        { status: 500 }
      )
    }

    console.log('=== SUCCESS ===')

    const answer = data.choices?.[0]?.message?.content || 'Sorry, I could not generate a response.'

    console.log('Answer length:', answer.length, 'characters')

    return NextResponse.json({
      answer,
      note: 'This response is generated by OpenAI GPT-4o-mini for educational purposes only.'
    })

  } catch (error) {
    console.error('=== AI API EXCEPTION ===')
    console.error('Error:', error)
    return NextResponse.json(
      { error: 'Internal server error', details: String(error) },
      { status: 500 }
    )
  }
}
